version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: run build file
          command: /bin/bash -x build.sh ${CIRCLE_SHA1} test
  test-cases:
    working_directory: ~/portal/src/app/client
    machine:
      # Ref: https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-2004:202111-02
    steps:
      - checkout:
          path: ~/portal
      - run:
          name: Installing prerequisites
          command: |-
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            nvm -v
      - run:
          name: node version 12
          command: 'nvm install 12.20.1'
      - run:
          name: Installing angular cli
          command: 'npm install -g @angular/cli@6.0.8 --no-progress'
      - run:
          name: remove node_modules
          command: 'rm -rf portal/src/app/client/node_modules/'
      - run:
          name: Installing npm deps
          command: 'npm install --no-progress'
      - run:
          name: ng lint and building
          command: 'mkdir -p /tmp/logs && node --max_old_space_size=6000 ./node_modules/@angular/cli/bin/ng build --prod --optimization=false --buildOptimizer=false | tee /tmp/logs/build.log'
      - run:
          name: Executing test cases
          command: 'npm run test-coverage | tee /tmp/logs/test_cases.log'
      - run:
          name: install sonar scanner
          command: npm install -g sonarqube-scanner
      - run:
         name: run sonar scanner
         command: 'cd ~/portal && sonar-scanner'
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-cases
