
version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: run build file
          command: /bin/bash -x build.sh ${CIRCLE_SHA1} test
  test-cases:
    working_directory: ~/portal/src/app/client
    docker:
      - image: sunbird/build:player
    steps:
      - checkout:
          path: ~/portal
      - run:
          name: Installing angular cli
          command: 'npm install -g @angular/cli@7.3.6'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Removing package-lock.json file and node_modules folder
          command: 'rm -rf package-lock.json ./node_modules'
      - run:
          name: Installing npm deps
          command: 'npm install'
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
      - run:
          name: building
          command: 'mkdir -p /tmp/logs && ng build --prod | tee /tmp/logs/build.log'
      - run:
          name: Executing test cases
          command: 'npm run test-coverage | tee /tmp/logs/test_cases.log'
      - run:
          name: install sonar scanner
          command: npm install -g sonarqube-scanner
      - run:
         name: run sonar scanner
         command: 'cd ~/portal && sonar-scanner'
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-cases
