version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Installing prerequisites
          command: |-
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            node --version
      - run:
          name: run build file
          command: /bin/bash -x build.sh ${CIRCLE_SHA1} test
  test-cases:
    working_directory: ~/portal/src/app/client
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout:
          path: ~/portal
      - run:
          name: Installing angular cli
          command: 'npm install -g @angular/cli@10.2.4 --no-progress'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing npm deps
          command: 'npm install --no-progress'
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
      - run:
          name: ng lint and building
          command: 'mkdir -p /tmp/logs && node --max_old_space_size=6000 ./node_modules/@angular/cli/bin/ng build --prod --optimization=false --buildOptimizer=false | tee /tmp/logs/build.log'
      - run:
          name: Executing test cases
          command: 'npm run test-coverage | tee /tmp/logs/test_cases.log'
      - run:
          name: Install  Node.js v14.20.1 with build in nvm tool
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v14 && nvm use v14.20.1 && nvm alias default v14.20.1
            node -v
      - run:
          name: Altered Node version
          command: 'node --version'
      - run:
          name: install sonar scanner
          command: npm install -g sonarqube-scanner
      - run:
         name: run sonar scanner
         command: 'cd ~/portal && sonar-scanner'
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-cases
