'use strict'
const env = process.env
const fs = require('fs')
const packageObj = JSON.parse(fs.readFileSync('package.json', 'utf8'))
let envVariables = {
  APPID: process.env.sunbird_environment + '.' + process.env.sunbird_instance + '.portal',
  sunbird_instance_name: env.sunbird_instance || 'Sunbird',
  DEFAULT_CHANNEL: env.sunbird_default_channel,
  PORTAL_API_WHITELIST_CHECK: env.sunbird_enable_api_whitelist || 'true',
  DEFAULT_CHANNEL: env.sunbird_default_channel || 'tn',
  PORTAL_PORT: env.sunbird_port || 3000,
  LEARNER_URL: env.sunbird_learner_player_url || 'https://dev.sunbirded.org/api/',
  CONTENT_URL: env.sunbird_content_player_url || 'https://dock.sunbirded.org/api/',
  CONTENT_PROXY_URL: env.sunbird_content_proxy_url || 'https://dock.sunbirded.org',
  PORTAL_REALM: env.sunbird_portal_realm || 'sunbird',
  PORTAL_AUTH_SERVER_URL: env.sunbird_portal_auth_server_url || 'https://dev.sunbirded.org/auth',
  PORTAL_AUTH_SERVER_CLIENT: env.sunbird_portal_auth_server_client || 'portal',
  PORTAL_API_AUTH_TOKEN: env.dock_api_auth_token || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiZDExNjYzN2Y5YjU0MWJiYjU3NDY3MTA2Yjk1YzllYSJ9.Bb8ThNzcBvhouPdtRa_UXnZgi3m2zZN5Skhke1_YlM0',
  SUNBIRD_PORTAL_API_AUTH_TOKEN: env.sunbird_api_auth_token || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJqd2RYTFhUZ2h2QklmZ3ZkTzBBUXZMTVlycE0zbTNsZSJ9.8mQZPm1ZiV78S1F9u215ANYEC_FhM363KDh5nCV1grs',
  PORTAL_ECHO_API_URL: env.sunbird_echo_api_url || 'https://dev.sunbirded.org/api/echo/',
  CONFIG_URL: env.sunbird_config_service_url || 'https://dev.sunbirded.org/api/config/',
  EKSTEP_ENV: env.ekstep_env || 'qa',
  DEVICE_REGISTER_API: process.env.sunbird_device_register_api || 'https://api.open-sunbird.org/v3/device/register/',
  DEVICE_PROFILE_API: process.env.sunbird_device_profile_api || 'https://staging.open-sunbird.org/api/v3/device/profile/',
  sunbird_theme: env.sunbird_theme || 'default',
  BUILD_NUMBER: packageObj.version + '.' + packageObj.buildHash,
  sunbird_portal_log_level: env.sunbird_portal_log_level || 'debug',
  sunbird_extcont_whitelisted_domains: env.sunbird_extcont_whitelisted_domains || 'youtube.com,youtu.be',
  sunbird_explore_button_visibility: env.sunbird_explore_button_visibility || 'true',
  sunbird_help_link_visibility: env.sunbird_help_link_visibility || 'false',
  sunbird_portal_user_upload_ref_link: env.sunbird_portal_user_upload_ref_link || 'http://www.sunbird.org/features-documentation/register_user',
  ENABLE_PERMISSION_CHECK: env.sunbird_enabless_permission_check || 0,
  CONFIG_SERVICE_ENABLED: env.config_service_enabled || false,
  CRYPTO_ENCRYPTION_KEY: env.crypto_encryption_key || '030702bc8696b8ee2aa71b9f13e4251e',
  LOG_FINGERPRINT_DETAILS: env.sunbird_log_fingerprint_details || 'true',
  SUNBIRD_PORTAL_BASE_URL: env.sunbird_portal_base_url,
  DOCK_CHANNEL: env.dock_channel || 'sunbird',
  sunbird_device_api: env.sunbird_device_api || 'https://staging.ntp.net.in/api/',
  dock_api_call_log_status: env.dock_api_call_log_status || false,
  SUNBIRD_PORTAL_URL: env.sunbird_portal_url,
  SUNBIRD_LEARNER_URL: env.sunbird_learner_url,
  DOCK_PROGRAM_SERVICE_URL: env.dock_program_service_url,
  DOCK_QUESTIONSET_ENABLE: env.dock_questionSet_enable || 'true',
  DOCK_SMS_URL: env.dock_sms_url || 'https://vdn.diksha.gov.in',
  DOCK_DEFAULT_FILE_SIZE: env.dock_default_file_size || 150,
  DOCK_DEFAULT_VIDEO_SIZE: env.dock_default_video_size || 15000,
  SUNBIRD_QUESTIONSET_CHILDREN_LIMIT: 500,
  SUNBIRD_COLLECTION_CHILDREN_LIMIT: 500,
  SUNBIRD_PROTO: env.sunbird_base_proto,
  OPENSABER_SERVICE_URL: env.opensaber_service_url || 'http://opensaber-service:8080',
  USE_SUNBIRD_KONG_TOKEN: env.use_sunbird_kong_token || 'true',
  sunbird_kong_refresh_token_api: env.sunbird_kong_refresh_token_api || '',
  SUNBIRD_TRANSCRIPT_SUPPORTED_LANGUAGES: env.sunbird_transcript_supported_languages || 'English, Hindi, Assamese, Bengali, Gujarati, Kannada, Malayalam, Marathi, Nepali, Odia, Punjabi, Tamil, Telugu, Urdu, Sanskrit, Maithili, Munda, Santali, Juang, Ho, Oriya',
  SUNBIRD_TRANSCRIPT_FILE_FORMAT: env.sunbird_transcript_file_format || 'srt',
  SUNBIRD_TRANSCRIPT_REQUIRED: env.sunbird_transcript_required || false,
  SUNBIRD_BULK_UPLOAD_NAME_LENGTH: env.sunbird_bulk_upload_name_length || '50',
  SUNBIRD_BULK_UPLOAD_DESC_LENGTH: env.sunbird_bulk_upload_description_length || '500',
  sunbird_accessibility_guidelines_url: env.sunbird_accessibility_guidelines_url || '',
  ALLOWED_FRAMEWORK_TYPES: env.allowed_framework_types || '',
  LOCAL_DEVELOPMENT: env.local_development || true,
  // TTL and Intervals
  CONFIG_REFRESH_INTERVAL: env.config_refresh_interval || 10,
  CONFIG_SERVICE_ENABLED: env.config_service_enabled || false,
  PORTAL_TELEMETRY_PACKET_SIZE: env.sunbird_telemetry_packet_size || 1000,
  PORTAL_AUTOCREATE_TRAMPOLINE_USER: env.sunbird_autocreate_trampoline_user || 'true',
  PORTAL_TRAMPOLINE_CLIENT_ID: env.sunbird_trampoline_client_id || 'trampoline',
  PORTAL_TRAMPOLINE_SECRET: env.sunbird_trampoline_secret,
  ENABLE_PERMISSION_CHECK: 1 || 0,
  PORTAL_SESSION_STORE_TYPE: env.sunbird_session_store_type || 'in-memory',
  PORTAL_CDN_URL: env.sunbird_portal_cdn_url || '',
  PORTAL_CLOUD_STORAGE_URL: env.portal_cloud_storage_url || 'https://dockstorage.blob.core.windows.net/content-service/',
  CONTENT_SERVICE_UPSTREAM_URL: env.sunbird_content_service_upstream_url || 'http://localhost:5000/',
  LEARNER_SERVICE_UPSTREAM_URL: env.sunbird_learner_service_upstream_url || 'http://localhost:9000/',
  DATASERVICE_URL: env.sunbird_dataservice_url || 'https://dock.sunbirded.org/api/',
  KEY_CLOAK_PUBLIC: env.sunbird_keycloak_public || 'true',
  KEY_CLOAK_REALM: env.sunbird_keycloak_realm || 'sunbird',
  CACHE_STORE: env.sunbird_cache_store || 'memory',
  CACHE_TTL: env.sunbird_cache_ttl || 1800,
  ANDROID_APP_URL: env.sunbird_android_app_url || 'http://www.sunbird.org',
  TELEMETRY_SERVICE_LOCAL_URL: env.sunbird_telemetry_service_local_url || 'http://telemetry-service:9001/',
  PORTAL_API_CACHE_TTL: env.sunbird_api_response_cache_ttl || '600',
  TENANT_CDN_URL: env.sunbird_tenant_cdn_url || '',
  CLOUD_STORAGE_URLS: env.sunbird_cloud_storage_urls,
  PORTAL_CASSANDRA_CONSISTENCY_LEVEL: env.sunbird_cassandra_consistency_level || 'one',
  PORTAL_CASSANDRA_REPLICATION_STRATEGY: env.sunbird_cassandra_replication_strategy || '{"class":"SimpleStrategy","replication_factor":1}',
  sunbird_azure_report_container_name: env.sunbird_azure_report_container_name || 'reports',
  sunbird_azure_account_name: env.sunbird_azure_account_name,
  sunbird_azure_account_key: env.sunbird_azure_account_key,
  sunbird_portal_cdn_blob_url: env.sunbird_portal_cdn_blob_url || '',
  sunbird_portal_video_max_size: env.sunbird_portal_video_max_size || '50',
  SUNBIRD_CONTEXTUAL_HELP_CONFIG: env.sunbird_contextual_help_config,
  // Default Language Configuration
  PORTAL_EXT_PLUGIN_URL: process.env.sunbird_ext_plugin_url || 'http://player_player:3000/plugin/',
  kp_content_service_base_url: env.sunbird_kp_content_service_base_url || 'https://dock.sunbirded.org/api/',
  kp_learning_service_base_url: env.sunbird_kp_learning_service_base_url || 'https://dock.sunbirded.org/api/',
  kp_assessment_service_base_url: env.sunbird_kp_assessment_service_base_url || 'https://dock.sunbirded.org/api/',
  sunbird_default_language: env.sunbird_portal_default_language || 'en',
  sunbird_primary_bundle_language: env.sunbird_portal_primary_bundle_language || 'en',
  SUNBIRD_CONTEXTUAL_HELP_CONFIG: '{"sourcing":{"manageUsers":{"url":"/help/contribute/administrator/manage-users/index.html","header":"Inviting users will allow you to assign them roles for projects","message":"You can invite users to your organization by clicking on Invite Users and sharing an invitation link with them"},"noUsersFound":{"url":"/help/contribute/how-to/how-to-make-users-part-of-contributor.html","header":"Inviting users will allow you to assign them roles for projects","message":"You can invite users to your organization by clicking on Invite Users and sharing an invitation link with them"},"reviewContributions":{"url":"/help/contribute/reviewer/review-contributions/index.html","header":"This table allow you to see a list of content pending for your review.","message":"Click on any unit to proceed with the review process"},"assignUsersToProject":{"url":"/help/contribute/how-to/how-to-assign-users-with-roles-to-contributor-projects.html","header":"This table allows you to see all the users available for this project and assign them relevant roles","message":"You can do so by clicking on Select Role next to a particular user and selecting their role from the dropdown."},"reviewNominations":{"url":"/help/contribute/reviewer/review-contributions/index.html","header":"This table allow you to see a list of contributor.","message":""}},"contribute":{"manageUsers":{"url":"/help/contribute/administrator/manage-users/index.html","header":"Inviting users will allow you to assign them roles for projects","message":"You can invite users to your organization by clicking on Invite Users and sharing an invitation link with them"},"noUsersFound":{"url":"/help/contribute/how-to/how-to-make-users-part-of-contributor.html","header":"Inviting users will allow you to assign them roles for projects","message":"You can invite users to your organization by clicking on Invite Users and sharing an invitation link with them"},"myProjects":{"url":"/help/contribute/contributor/enrol/index.html","header":"You can use this space to view all the projects assigned to you, along with your designated role.","message":"You can contribute or review content based on the requirements"},"myProjectsNotFound":{"url":"/help/contribute/how-to/how-to-nominate-for-sourcing-project.html","header":"Seems like your organization has no projects yet.","message":""},"allProjectNomations":{"url":"/help/contribute/how-to/how-to-nominate-for-sourcing-project.html","header":"This space allows you to upload your content samples, in order to nominate to this particular project.","message":""},"myProjectContribute":{"url":"/help/contribute/how-to/how-to-nominate-for-sourcing-project.html","header":"This space allows you to see a list of content pending for your contribution in this project","message":"Click on any unit to proceed with the contribution process."}}}',
  learner_Service_Local_BaseUrl: env.sunbird_learner_service_local_base_url || 'http://learner-service:9000',
  content_Service_Local_BaseUrl: env.sunbird_content_service_local_base_url || 'http://content-service:5000',
  sunbird_explore_button_visibility: env.sunbird_explore_button_visibility || 'true',
  sunbird_help_link_visibility: env.sunbird_help_link_visibility || 'true',
  sunbird_extcont_whitelisted_domains: env.sunbird_extcont_whitelisted_domains || 'youtube.com,youtu.be',
  sunbird_portal_user_upload_ref_link: env.sunbird_portal_user_upload_ref_link || 'http://www.sunbird.org/features-documentation/register_user',
  GOOGLE_OAUTH_CONFIG: {
    clientId: env.sunbird_google_oauth_clientId || '671624305038-e8pbpmidst6lf0j5qplp6g6odan3lbf5.apps.googleusercontent.com' || '903729999899-7vcrph3vro36ot43j1od8u6he9jjend0.apps.googleusercontent.com',
    clientSecret: env.sunbird_google_oauth_clientSecret || 'mDO2MM68iW23f47ZFtvREld9' || 'BAEAYRv7voTByz5rOKkbIE3u'
  },
  KEYCLOAK_GOOGLE_CLIENT: {
    clientId: env.sunbird_google_keycloak_client_id || 'google-auth',
    secret: env.sunbird_google_keycloak_secret || '8486df4b-2ec0-4249-92d8-5f3a7064cd07'
  },
  sunbird_google_captcha_site_key: env.sunbird_google_captcha_site_key || '6Ldcf4EUAAAAAMrKQSviNtEzMretoDgeAUxqJv7d',
  sunbird_azure_report_container_name: env.sunbird_azure_report_container_name || 'reports',
  sunbird_azure_account_name: env.sunbird_azure_account_name || 'sunbirddev',
  sunbird_azure_account_key: 'k8NzvVqH0WSwCARJZo2h6G28AT2775MbrhMi9Akt4HNdYH009WVWmjjs31L08VEMnvRxas1DU7UM3/KtuMxpVg==',
  sunbird_portal_health_check_enabled: env.sunbird_health_check_enable || 'true',
  sunbird_learner_service_health_status: 'true',
  sunbird_content_service_health_status: 'true',
  sunbird_portal_cassandra_db_health_status: 'true',
  sunbird_portal_player_cdn_enabled: env.sunbird_portal_player_cdn_enabled,
  sunbird_processing_kafka_host: process.env.sunbird_processing_kafka_host,
  sunbird_sso_kafka_topic: process.env.sunbird_sso_kafka_topic,
  sunbird_portal_offline_tenant: env.sunbird_portal_offline_tenant,
  sunbird_portal_offline_supported_languages: env.sunbird_portal_offline_supported_languages,
  sunbird_portal_offline_app_release_date: env.sunbird_portal_offline_app_release_date,
  sunbird_portal_offline_app_version: env.sunbird_portal_offline_app_version,
  sunbird_portal_offline_app_download_url: env.sunbird_portal_offline_app_download_url,
  sunbird_portal_cdn_blob_url: env.sunbird_portal_cdn_blob_url || '',
  sunbird_portal_log_level: env.sunbird_portal_log_level || 'debug',
  SUNBIRD_PUBLIC_STORAGE_ACCOUNT_NAME: env.sunbird_public_storage_account_name || 'dasd',
  KEYCLOAK_GOOGLE_ANDROID_CLIENT: {
    clientId: env.sunbird_google_android_keycloak_client_id,
    secret: env.sunbird_google_android_keycloak_secret
  },
  KEYCLOAK_TRAMPOLINE_ANDROID_CLIENT: {
    clientId: env.sunbird_trampoline_android_keycloak_client_id,
    secret: env.sunbird_trampoline_android_keycloak_secret
  },
  KEYCLOAK_ANDROID_CLIENT: {
    clientId: env.sunbird_android_keycloak_client_id || 'android',
  },
  DOCK_WORKSPACE_PROXY: env.dock_workspace_proxy || true,
  FORM_URL: env.form_url || 'https://dev.sunbirded.org/api/'
}
envVariables.PORTAL_CASSANDRA_URLS = (env.sunbird_cassandra_urls && env.sunbird_cassandra_urls !== '')
  ? env.sunbird_cassandra_urls.split(',') : ['localhost']
module.exports = envVariables