export const userDetail = 
{
  "id": "api.user.search",
  "ver": "v1",
  "ts": "2020-08-31 08:04:59:441+0000",
  "params": {
      "resmsgid": null,
      "msgid": "f194a58c-7103-9101-9683-1d63f346db7d",
      "err": null,
      "status": "success",
      "errmsg": null
  },
  "responseCode": "OK",
  "result": {
      "response": {
          "count": 2,
          "content": [
              {
                  "lastName": null,
                  "tcStatus": null,
                  "maskedPhone": null,
                  "rootOrgName": "Christ_University",
                  "roles": [
                      "PUBLIC"
                  ],
                  "channel": "CH123",
                  "updatedDate": null,
                  "prevUsedPhone": "",
                  "stateValidated": true,
                  "isDeleted": false,
                  "organisations": [
                      {
                          "updatedBy": null,
                          "organisationId": "01307938306521497658",
                          "orgName": "Christ_University",
                          "addedByName": null,
                          "addedBy": null,
                          "roles": [
                              "CONTENT_REVIEWER",
                              "BOOK_REVIEWER",
                              "PUBLIC"
                          ],
                          "approvedBy": null,
                          "updatedDate": null,
                          "userId": "9ef979da-7705-4550-98f1-779ef90e79a8",
                          "approvaldate": null,
                          "isDeleted": false,
                          "parentOrgId": null,
                          "hashTagId": "01307938306521497658",
                          "isRejected": null,
                          "position": null,
                          "id": "013079427143655424228",
                          "orgjoindate": "2020-08-05 06:34:51:622+0000",
                          "isApproved": null,
                          "orgLeftDate": null
                      }
                  ],
                  "managedBy": null,
                  "provider": null,
                  "flagsValue": 6,
                  "maskedEmail": "jn***@yopamil.com",
                  "id": "9ef979da-7705-4550-98f1-779ef90e79a8",
                  "tempPassword": null,
                  "recoveryEmail": "",
                  "email": "jn***@yopamil.com",
                  "selectedRole": "CONTRIBUTOR",
                  "identifier": "9ef979da-7705-4550-98f1-779ef90e79a8",
                  "thumbnail": null,
                  "updatedBy": null,
                  "accesscode": null,
                  "profileSummary": null,
                  "phoneVerified": false,
                  "tcUpdatedDate": null,
                  "locationIds": [],
                  "registryId": null,
                  "recoveryPhone": "",
                  "userName": "jnc68@yopamil.com",
                  "rootOrgId": "01307938306521497658",
                  "prevUsedEmail": "",
                  "firstName": "jnc68",
                  "lastLoginTime": null,
                  "emailVerified": true,
                  "tncAcceptedOn": null,
                  "framework": {},
                  "createdDate": "2020-08-05 06:34:50:037+0000",
                  "phone": "",
                  "createdBy": "bb193071-02fb-41f0-9b8c-1b03ecdaf729",
                  "currentLoginTime": null,
                  "userType": "OTHER",
                  "tncAcceptedVersion": null,
                  "status": 1
              },
              {
                  "lastName": null,
                  "tcStatus": null,
                  "maskedPhone": null,
                  "rootOrgName": "Christ_University",
                  "roles": [
                      "PUBLIC"
                  ],
                  "channel": "CH123",
                  "updatedDate": null,
                  "prevUsedPhone": "",
                  "stateValidated": true,
                  "isDeleted": false,
                  "organisations": [
                      {
                          "updatedBy": null,
                          "organisationId": "01307938306521497658",
                          "orgName": "Christ_University",
                          "addedByName": null,
                          "addedBy": null,
                          "roles": [
                              "CONTENT_CREATOR",
                              "BOOK_CREATOR",
                              "PUBLIC"
                          ],
                          "approvedBy": null,
                          "updatedDate": null,
                          "userId": "77f36572-b372-4630-9b82-a56f35d9b61a",
                          "approvaldate": null,
                          "isDeleted": false,
                          "parentOrgId": null,
                          "hashTagId": "01307938306521497658",
                          "isRejected": null,
                          "position": null,
                          "id": "013079421882687488184",
                          "orgjoindate": "2020-08-05 06:22:18:256+0000",
                          "isApproved": null,
                          "orgLeftDate": null
                      }
                  ],
                  "managedBy": null,
                  "provider": null,
                  "flagsValue": 6,
                  "maskedEmail": "jn***@yopamil.com",
                  "id": "77f36572-b372-4630-9b82-a56f35d9b61a",
                  "tempPassword": null,
                  "recoveryEmail": "",
                  "email": "jn***@yopamil.com",
                  "identifier": "77f36572-b372-4630-9b82-a56f35d9b61a",
                  "thumbnail": null,
                  "updatedBy": null,
                  "accesscode": null,
                  "profileSummary": null,
                  "phoneVerified": false,
                  "tcUpdatedDate": null,
                  "locationIds": [],
                  "registryId": null,
                  "recoveryPhone": "",
                  "userName": "jnc24@yopamil.com",
                  "rootOrgId": "01307938306521497658",
                  "prevUsedEmail": "",
                  "firstName": "jnc24",
                  "lastLoginTime": null,
                  "emailVerified": true,
                  "tncAcceptedOn": null,
                  "framework": {},
                  "createdDate": "2020-08-05 06:22:16:427+0000",
                  "phone": "",
                  "createdBy": "bb193071-02fb-41f0-9b8c-1b03ecdaf729",
                  "currentLoginTime": null,
                  "userType": "OTHER",
                  "tncAcceptedVersion": null,
                  "status": 1
              }
          ]
      }
  }
}

export const chunkedUserList  = [
[ {
    "lastName": null,
    "tcStatus": null,
    "maskedPhone": null,
    "rootOrgName": "Christ_University",
    "roles": [
        "PUBLIC"
    ],
    "channel": "CH123",
    "updatedDate": null,
    "prevUsedPhone": "",
    "stateValidated": true,
    "isDeleted": false,
    "organisations": [
        {
            "updatedBy": null,
            "organisationId": "01307938306521497658",
            "orgName": "Christ_University",
            "addedByName": null,
            "addedBy": null,
            "roles": [
                "CONTENT_REVIEWER",
                "BOOK_REVIEWER",
                "PUBLIC"
            ],
            "approvedBy": null,
            "updatedDate": null,
            "userId": "9ef979da-7705-4550-98f1-779ef90e79a8",
            "approvaldate": null,
            "isDeleted": false,
            "parentOrgId": null,
            "hashTagId": "01307938306521497658",
            "isRejected": null,
            "position": null,
            "id": "013079427143655424228",
            "orgjoindate": "2020-08-05 06:34:51:622+0000",
            "isApproved": null,
            "orgLeftDate": null
        }
    ],
    "managedBy": null,
    "provider": null,
    "flagsValue": 6,
    "maskedEmail": "jn***@yopamil.com",
    "id": "9ef979da-7705-4550-98f1-779ef90e79a8",
    "tempPassword": null,
    "recoveryEmail": "",
    "email": "jn***@yopamil.com",
    "selectedRole": "CONTRIBUTOR",
    "identifier": "9ef979da-7705-4550-98f1-779ef90e79a8",
    "thumbnail": null,
    "updatedBy": null,
    "accesscode": null,
    "profileSummary": null,
    "phoneVerified": false,
    "tcUpdatedDate": null,
    "locationIds": [],
    "registryId": null,
    "recoveryPhone": "",
    "userName": "jnc68@yopamil.com",
    "rootOrgId": "01307938306521497658",
    "prevUsedEmail": "",
    "firstName": "jnc68",
    "lastLoginTime": null,
    "emailVerified": true,
    "tncAcceptedOn": null,
    "framework": {},
    "createdDate": "2020-08-05 06:34:50:037+0000",
    "phone": "",
    "createdBy": "bb193071-02fb-41f0-9b8c-1b03ecdaf729",
    "currentLoginTime": null,
    "userType": "OTHER",
    "tncAcceptedVersion": null,
    "status": 1
}],
[
{
    "lastName": null,
    "tcStatus": null,
    "maskedPhone": null,
    "rootOrgName": "Christ_University",
    "roles": [
        "PUBLIC"
    ],
    "channel": "CH123",
    "updatedDate": null,
    "prevUsedPhone": "",
    "stateValidated": true,
    "isDeleted": false,
    "organisations": [
        {
            "updatedBy": null,
            "organisationId": "01307938306521497658",
            "orgName": "Christ_University",
            "addedByName": null,
            "addedBy": null,
            "roles": [
                "CONTENT_CREATOR",
                "BOOK_CREATOR",
                "PUBLIC"
            ],
            "approvedBy": null,
            "updatedDate": null,
            "userId": "77f36572-b372-4630-9b82-a56f35d9b61a",
            "approvaldate": null,
            "isDeleted": false,
            "parentOrgId": null,
            "hashTagId": "01307938306521497658",
            "isRejected": null,
            "position": null,
            "id": "013079421882687488184",
            "orgjoindate": "2020-08-05 06:22:18:256+0000",
            "isApproved": null,
            "orgLeftDate": null
        }
    ],
    "managedBy": null,
    "provider": null,
    "flagsValue": 6,
    "maskedEmail": "jn***@yopamil.com",
    "id": "77f36572-b372-4630-9b82-a56f35d9b61a",
    "tempPassword": null,
    "recoveryEmail": "",
    "email": "jn***@yopamil.com",
    "identifier": "77f36572-b372-4630-9b82-a56f35d9b61a",
    "thumbnail": null,
    "updatedBy": null,
    "accesscode": null,
    "profileSummary": null,
    "phoneVerified": false,
    "tcUpdatedDate": null,
    "locationIds": [],
    "registryId": null,
    "recoveryPhone": "",
    "userName": "jnc24@yopamil.com",
    "rootOrgId": "01307938306521497658",
    "prevUsedEmail": "",
    "firstName": "jnc24",
    "lastLoginTime": null,
    "emailVerified": true,
    "tncAcceptedOn": null,
    "framework": {},
    "createdDate": "2020-08-05 06:22:16:427+0000",
    "phone": "",
    "createdBy": "bb193071-02fb-41f0-9b8c-1b03ecdaf729",
    "currentLoginTime": null,
    "userType": "OTHER",
    "tncAcceptedVersion": null,
    "status": 1
}
]
]

export const telemetryData =  {
    context: {
        env: 'workspace'
    },
    edata: {
        type: 'list',
        pageid: '',
        subtype: 'scroll',
        uri: '',
        visits: []
    }
}